name=SparkFun_FS3000_Arduino_Library
version=2.0.0
author=SparkFun Electronics
maintainer=SparkFun Electronics
sentence=A library to control the SparkFun Air Velocity Sensor Breakout - FS3000 (Qwiic).
paragraph=Reads data back from sensor and checks the checksum. Supports both FS3000-1005 and FS3000-1015 versions. Version 2.0 and above of this library uses the SparkFun Toolkit.
category=Sensors
url=https://github.com/sparkfun/SparkFun_FS3000_Arduino_Library
architectures=*
depends=SparkFun Toolkit (>=1.2.0)
